steps:

- name: 'gcr.io/$PROJECT_ID/yaml-snippets-env'
  args: ['npm', 'install']

- name: 'gcr.io/$PROJECT_ID/yaml-snippets-env'
  args: ['npm', 'run', 'build']
  env: [
      'VUE_APP_FIREBASE_API_KEY=${_VUE_APP_FIREBASE_API_KEY}',
      'VUE_APP_FIREBASE_AUTH_DOMAIN=${_VUE_APP_FIREBASE_AUTH_DOMAIN}',
      'VUE_APP_FIREBASE_DATABASE_URL=${_VUE_APP_FIREBASE_DATABASE_URL}',
      'VUE_APP_FIREBASE_PROJECT_ID=${_VUE_APP_FIREBASE_PROJECT_ID}',
      'VUE_APP_FIREBASE_STORAGE_BUCKET=${_VUE_APP_FIREBASE_STORAGE_BUCKET}',
      'VUE_APP_FIREBASE_MESSAGE_SENDER_ID=${_VUE_APP_FIREBASE_MESSAGE_SENDER_ID}',
      'VUE_APP_FIREBASE_MEASUREMENT_ID=${_VUE_APP_FIREBASE_MEASUREMENT_ID}',
      'VUE_APP_FIREBASE_APP_ID=${_VUE_APP_FIREBASE_APP_ID}',
      'VUE_APP_ALGOLIA_APP_ID=${_VUE_APP_ALGOLIA_APP_ID}',
      'VUE_APP_ALGOLIA_SEARCH_API_KEY=${_VUE_APP_ALGOLIA_SEARCH_API_KEY}'
  ]

- name: 'gcr.io/$PROJECT_ID/yaml-snippets-env'
  args: ['firebase', 'deploy', '--debug', '--token', '${_FIREBASE_TOKEN}']
